export enum GQLErrorCode {
  CUSTOM_NOT_FOUND = "CUSTOM_NOT_FOUND",
  CUSTOM_BAD_USER_INPUT = "CUSTOM_BAD_USER_INPUT",
  CUSTOM_UNAUTHORIZED = "CUSTOM_UNAUTHORIZED",
  CUSTOM_BAD_REQUEST = "CUSTOM_BAD_REQUEST"
}
