compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs

npmRegistryServer: "https://registry.npmjs.org"

npmPublishAccess: "public"

npmScopes:
  humaapi:
    npmPublishRegistry: 'https://registry.npmjs.org'
    npmAlwaysAuth: true
    npmAuthToken: ${HM_NPM_TOKEN}

  