compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@mantine/styles@*":
    dependencies:
      "@emotion/cache": ">=11.10.5"
      "@emotion/react": ">=11.10.5"
      "@emotion/serialize": ">=1.1.1"
      "@emotion/utils": ">=1.2.0"
  "@remix-run/dev@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/instrumenter@*":
    dependencies:
      react: ">=18.2.0"
      react-dom: ">=18.2.0"
  local-pkg@*:
    dependencies:
      jsdom: ">=20.0.3"
  storybook@*:
    dependencies:
      react: ">=18.2.0"
      react-dom: ">=18.2.0"

yarnPath: .yarn/releases/yarn-4.4.1.cjs
